name: Base Java

on:
  workflow_call:
    inputs:
      use-snapshots:
        description: "Defines if maven should use a snapshot build"
        default: false
        required: false
        type: boolean
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      gradle-tasks:
        description: "tasks the gradle action should run"
        default: build
        required: false
        type: string
      use-mirror:
        description: "Injects a mirror maven before everything else"
        default: true
        required: false
        type: boolean
    secrets:
      saps-token:
        required: false
      nanite-token:
        required: false
      curse-token:
        required: false
      modrinth-token: 
        required: false
      github-token:
        required: false
      s3-access-key:
        required: true
      s3-secret-key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ inputs.java-version }}
      - uses: tespkg/actions-cache@v1
        with:
          endpoint: cdn.nanite.dev
          accessKey: ${{ secrets.s3-access-key }}
          secretKey: ${{ secrets.s3-secret-key }}
          bucket: actions-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle.properties') }}-${{ hashFiles('**/settings.gradle') }}
          path: |
            .gradle
            **/.gradle
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Inject mirror
        if: ${{ inputs.use-mirror == true }}
        run: |
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTION_PATH/init.gradle
          ls -la $GITHUB_ACTION_PATH
          echo "allprojects {\n\trepositories {\n\t\tmaven { url "https://maven.saps.dev/mirror" }\n\t}\n}" > $GITHUB_ACTION_PATH/init.gradle
          ls -la
          cat $GITHUB_ACTION_PATH/init.gradle
      - name: Run gradle tasks [${{ inputs.gradle-tasks }}]
        uses: gradle/gradle-build-action@v2
        env:
          SNAPSHOT: ${{ inputs.use-snapshots }}
          SAPS_TOKEN: ${{ secrets.saps-token }}
          NANITE_TOKEN: ${{ secrets.nanite-token }}
          CURSE_TOKEN: ${{ secrets.curse-token }}
          MODRINTH_TOKEN: ${{ secrets.modrinth-token }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          arguments: ${{ inputs.gradle-tasks }}
          cache-disabled: true # We'll use our own
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build-output
          path: ./**/libs/*.jar
