name: Standard release

on:
  workflow_call:
    inputs:
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      gradle-tasks:
        description: "The name of the task to run for curseforge to publish, leave empty to not publish to curseforge"
        default: "publish publishMods"
        required: false
        type: string
    secrets:
      saps-token:
        required: false
      nanite-token:
        required: false
      curse-token:
        required: false
      modrinth-token: 
        required: false
      github-token:
        required: false

jobs:
  build:
    name: Build
    uses: ./.github/workflows/base-java.yml
    with:
      java-version: ${{ inputs.java-version }}
      use-snapshots: false
      gradle-tasks: ${{ inputs.gradle-tasks }}
    secrets: inherit
