name: Standard MPP

on:
  workflow_call:
    inputs:
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      changelog-file:
        description: "Location of the changelog file"
        default: "./CHANGELOG.md"
        required: false
        type: string
      curse-publish-task:
        description: "The name of the task to run for curseforge to publish, leave empty to not publish to curseforge"
        default: "publishMods"
        required: false
        type: string
      release-files:
        description: "The files to include in a github release, this is limited to a single input so get creative with your glob patterns"
        default: "**/build/libs/*.jar"
        required: false
        type: string
      release-to-github:
        default: true
        required: false
        type: boolean
        description: "If the project should release to github"
    secrets:
      saps-token:
        required: false
      nanite-token:
        required: false
      curse-token:
        required: false
      modrinth-token: 
        required: false
      github-token:
        required: false

jobs:
  build:
    name: Build & release
    uses: ./.github/workflows/base-java.yml
    with:
      java-version: ${{ inputs.java-version }}
      use-snapshots: false
      gradle-tasks: build publish ${{ inputs.curse-publish-task }}
    secrets: inherit
  release:
    if: startsWith(github.ref, 'refs/tags/') && inputs.release-to-github
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gradle-build-output
      - name: Release to Github
        uses: "softprops/action-gh-release@v2"
        with:
          body_path: ${{ inputs.changelog-file }}
          prerelease: false
          files: |
            ${{ inputs.release-files }}
