name: Standard Arch Release

on:
  workflow_call:
    inputs:
      java-version:
        description: "The java version"
        default: 17
        required: false
        type: number
      changelog-file:
        description: "Location of the changelog file"
        default: "CHANGELOG.md"
        required: false
        type: string
    secrets: 
      saps-token: 
        required: true

jobs:
  release-arch:
    name: Build & release
    uses: ./.github/workflows/standard-release.yml
    with:
      java-version: ${{ inputs.java-version }}
      changelog-file: ${{ inputs.changelog-file }}
      curse-publish-task: "curseforgePublish"
      release-files: ./+(forge|fabric)/build/libs/*+@(mc+([0-9]).+([0-9]).+([0-9])).jar
    secrets: inherit
      
